grafana:
  enabled: true
  service:
    type: ClusterIP
prometheus:
  prometheusSpec:
    enableFeatures: ["remote-write-receiver"]
    scrapeInterval: 15s
    evaluationInterval: 15s
    additionalArgs:
      - name: web.enable-remote-write-receiver
        value: ""