apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    purpose: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: k6-operator
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: k6-operator
    meta.helm.sh/release-namespace: k6-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
  labels:
    purpose: sample-app