apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: timesheets-load
  namespace: k6-operator
spec:
  parallelism: 1
  script:
    localFile: /scripts/tests/timesheets.js
  arguments: --tag env=local --tag plan=timesheets --tag build=${BUILD_TAG}
  runner:
    image: k6-runner:demo
    env:
      - name: BASE_URL
        value: "https://httpbin.test.k6.io"
      - name: K6_OUT
        value: "experimental-prometheus-rw"
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: "http://kps-kube-prometheus-stack-prometheus.monitoring.svc:9090/api/v1/write"
      - name: K6_PROMETHEUS_RW_TREND_BUCKETS
        value: "0.01,0.05,0.1,0.25,0.5,0.75,1,2.5,5,10"
      - name: K6_PROMETHEUS_RW_TREND_STATS
        value: "count,sum,min,max,med,p(90),p(95),p(99)"
      - name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
        value: "false"
      - name: K6_PROMETHEUS_RW_HISTOGRAM_BUCKETS
        value: "0.05,0.1,0.2,0.5,1,2,5"